// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"wire-poc/House"
)

// Injectors from Wire.go:

func Initialise() (War, error) {
	stark := ProvideStarks()
	lannisters := ProvideLannisters()
	war := NewWar(stark, lannisters)
	return war, nil
}

// Wire.go:

func ProvideStarks() House.Stark {
	return House.Stark{}
}

func ProvideLannisters() House.Lannisters {
	return House.Lannisters{}
}

func NewWar(h1 House.Stark, h2 House.Lannisters) War {
	return War{house1: h1, house2: h2}
}
