// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"wire-poc/House"
)

// Injectors from Wire.go:

func Initialize() (War, error) {
	stark, err := NewStarkProvider()
	if err != nil {
		return War{}, err
	}
	lannisters, err := NewLannisterProvider()
	if err != nil {
		return War{}, err
	}
	beyondWall, err := NewBeyondWallProvider()
	if err != nil {
		return War{}, err
	}
	war := NewWar(stark, lannisters, beyondWall)
	return war, nil
}

func InitializeMock() (MockWar, error) {
	stark, err := NewStarkProvider()
	if err != nil {
		return MockWar{}, err
	}
	lannisters, err := NewLannisterProvider()
	if err != nil {
		return MockWar{}, err
	}
	mockBeyondWall := ProvideMockBeyondWall()
	mockWar := NewMockWar(stark, lannisters, mockBeyondWall)
	return mockWar, nil
}

func NewStarkProvider() (House.Stark, error) {
	stark := ProvideStarks()
	return stark, nil
}

func NewLannisterProvider() (House.Lannisters, error) {
	lannisters := ProvideLannisters()
	return lannisters, nil
}

func NewBeyondWallProvider() (House.BeyondWall, error) {
	beyondWall := ProvideBeyondWall()
	return beyondWall, nil
}
