// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"wire-poc/House"
)

// Injectors from Wire.go:

func Initialize() (War, error) {
	stark, err := NewStarkProvider()
	if err != nil {
		return War{}, err
	}
	lannisters, err := NewLannisterProvider()
	if err != nil {
		return War{}, err
	}
	beyondWall := ProvideBeyondWall()
	war := War{
		House1: stark,
		House2: lannisters,
		House3: beyondWall,
	}
	return war, nil
}

func InitializeMock() (War, error) {
	stark, err := NewStarkProvider()
	if err != nil {
		return War{}, err
	}
	lannisters, err := NewLannisterProvider()
	if err != nil {
		return War{}, err
	}
	mockBeyondWall := ProvideMockBeyondWall()
	war := NewWar(stark, lannisters, mockBeyondWall)
	return war, nil
}

func NewStarkProvider() (House.Stark, error) {
	stark := ProvideStarks()
	return stark, nil
}

func NewLannisterProvider() (House.Lannisters, error) {
	lannisters := ProvideLannisters()
	return lannisters, nil
}
